version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  back:
    build:
      context: ./seccube-back
    restart: always
    ports:
      - 8081:8081
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  front:
    build:
      context: ./seccube-front
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
